[supervisord]
nodaemon=true
user=root

[program:crontab]
command=node /crontab-ui/scheduler.js
user=node
stderr_logfile = /var/log/crontab-stderr.log
stdout_logfile = /var/log/crontab-stdout.log

[program:crontabui]
command=node /crontab-ui/bootstrap.js
user=node
stderr_logfile = /var/log/crontabui-stderr.log
stdout_logfile = /var/log/crontabui-stdout.log
